name: ETF NAV Updater

on:
  schedule:
    - cron: '00 14 * * 1-5'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-nav:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas requests

      - name: Generate ETF NAV File
        run: |
          python etf_nav.py

      - name: Commit Updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add ETF_NAV.csv

          git diff --staged --quiet || git commit -m "Update ETF NAV"

          git push
